convertor/urls.py
from django.urls import path
from .views import upload_file, extract_pdf_tables, get_all_result,index

urlpatterns = [
    path('',index),
    path("api/upload", upload_file, name="upload"),
    path('api/extract-pdf-tables', extract_pdf_tables, name='extract_pdf_tables'),
    path("api/get-all", get_all_result, name="get-all"),
]

gt_convertor/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("convertor.urls",))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns() 

convertor/models.py
from django.db import models

# Create your models here.
class ReceiptFile(models.Model):
    """Model for storing receipt file"""
    file = models.FileField(upload_to='receipts/')
    uploaded_at = models.DateTimeField(auto_now_add=True)
    converted_csv = models.FileField(upload_to='receipts/converted_csv/', null=True, blank=True)
    status = models.CharField(max_length=100, default="Failed To convert")    

    def __str__(self):
        return self.file.name
    
class PDFFile(models.Model):
    file = models.FileField(upload_to='receipts/')
    timestamp = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.file.name

class ConvertedFile(models.Model):
    pdf_file = models.OneToOneField(PDFFile, on_delete=models.CASCADE)
    csv_file = models.FileField(upload_to='receipts/converted_csv/')
    timestamp = models.DateTimeField(auto_now_add=True)

convertor/forms.py
# forms.py

from django import forms
from .models import ReceiptFile

class ReceiptFileForm(forms.ModelForm):
    file = forms.FileField(required=False)
    class Meta:
        model = ReceiptFile
        fields = ['file']

convertor/views.py
from django.conf import settings
from django.http import JsonResponse
from django.http import JsonResponse
from django.shortcuts import render
import requests
import csv
import pdfplumber
from django.views.decorators.csrf import csrf_exempt
from django.forms.models import model_to_dict
from .models import ConvertedFile,PDFFile
from datetime import *
from .signals import convert_file
import os

# BACKEND_URL = 'http://localhost:8000/media/'
BACKEND_URL = 'https://file-converter-0ndt.onrender.com/media/'


def index(request):
    # response = requests.get('http://localhost:8000/api/get-all')
    response = requests.get('https://file-converter-0ndt.onrender.com/api/get-all')
    api_data = response.json()
    context = {
        'receipt_files':api_data["data"]
    }
    return render(request,'convert.html', context)


@csrf_exempt
def get_all_result(request):
    if request.method == 'GET':
        try:
            converted_files = ConvertedFile.objects.all().order_by('-timestamp')
            
            # Serialize the model instances into dictionaries
            converted_files_data = []
            for converted_file in converted_files:
                converted = {
                    'pdf_file': {
                        'id': converted_file.pdf_file.id,
                        'file': converted_file.pdf_file.file.url,
                        'timestamp': converted_file.pdf_file.timestamp.isoformat(),
                    },
                    'csv_file': converted_file.csv_file.url,
                    'timestamp': converted_file.timestamp.isoformat(),
                }
                converted_files_data.append(converted)            
            return JsonResponse({'status': True,'data':converted_files_data},status=200)
        except Exception as e:
            return JsonResponse({'status': False},status=200)
    else:
        return JsonResponse({'error': 'Invalid request'}, status=500)



@csrf_exempt
def upload_file(request):
    if request.method == 'POST':       
        pdf_file = request.FILES['pdf_file']
        print(pdf_file)

        leftMargin = request.POST.get("x1")
        print(leftMargin)

        bottomMargin = request.POST.get("y2")
        print(bottomMargin)

        rightMargin = request.POST.get("x2")
        print(rightMargin)
        
        topMargin = request.POST.get("y1")
        print(topMargin)

        return convert_file(pdf_file,int(leftMargin),int(bottomMargin),int(rightMargin),int(topMargin))
    
@csrf_exempt
def extract_pdf_tables(request):
    if request.method == 'POST' and request.FILES.get('pdf_file'):
        try:
            pdf_file = request.FILES['pdf_file']  
            # Save the uploaded PDF file to storage
            pdf_file_instance = PDFFile.objects.create(file=pdf_file)
            # Read PDF file
            with pdfplumber.open(pdf_file) as pdf:
                pdf_data = []
                csv_data=[]
                for page in pdf.pages:
                    for table in page.extract_tables():
                        for row in table:
                            while None in row:
                                row.remove(None)
                            pdf_data.append(row)
                for row in pdf_data:
                    if len(row) < 25 and len(row)>14:
                        # print(row)
                        csv_data.append(row)
                        
            # Convert to CSV format
            file_name = os.path.basename(pdf_file_instance.file.path)
            print("===========================")
            print(pdf_file_instance.file.path)
            file_name = file_name.replace(".pdf", "")
            converted_csv = os.path.join(settings.MEDIA_ROOT, 'receipts', 'converted_csv')
            csv_filename = f"{file_name}.csv"
            csv_file_path = f"{csv_filename}"
            csv_file_path = os.path.join(converted_csv, f'{csv_filename}')
            csv_downloading_path = '/' + os.path.join(*csv_file_path.split('/')[-3:])            
            # print(converted_csv,"\n",csv_filename,"\n",csv_file_path,"\n",csv_downloading_path)
            with open(csv_file_path, 'w', newline='') as csv_file:
                writer = csv.writer(csv_file)
                for row in csv_data:
                    writer.writerow(row)
            # Save the converted CSV file to storage
            converted_file_instance = ConvertedFile.objects.create(
                pdf_file=pdf_file_instance,
                csv_file=csv_downloading_path
            )
            converted_file_instance.save()
            return JsonResponse({'pdf_file_path': pdf_file_instance.file.url, 'csv_file_path': converted_file_instance.csv_file.url, 'timestamp': converted_file_instance.timestamp}, status=200)
        
        except Exception as e:
            return JsonResponse({'error': str(e)}, status=500)
    else:
        return JsonResponse({'error': 'Invalid request'}, status=400)

convertor/templates/convert.html
<!-- templates/upload_receipt_file.html -->

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Upload Receipt File</title>

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
        <!-- Cropper CSS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.12/cropper.min.css">
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <!-- Cropper JS -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.12/cropper.min.js"></script>
        <!-- PDF.js -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.11.338/pdf.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>


        <style>
      body {
        padding: 20px;
      }

      h2 {
        color: #007bff; /* Bootstrap's primary color */
      }

      form {
        margin-bottom: 20px;
      }

      table {
        width: 100%;
        margin-top: 20px;
        border-collapse: collapse;
      }

      th,
      td {
        padding: 10px;
        text-align: left;
        border: 1px solid #dee2e6; /* Bootstrap's table border color */
      }

      th {
        background-color: #007bff; /* Bootstrap's primary color */
        color: #fff;
      }

      tbody tr:hover {
        background-color: #f8f9fa; /* Bootstrap's table hover color */
      }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-12">


                 <!-- Upload Receipt File -->
<div class="container mt-5">
  <div class="row">
      <div class="col-md-6 offset-md-3">
          <h2 class="mb-4">Upload Files</h2>
          <form id="uploadForm" method="post" enctype="multipart/form-data">
              <div class="form-group">
                  <input type="file" class="form-control" id="fileInput" name="pdf_file" accept="image/*,application/pdf" required>
              </div>
              <div class="form-group">
                  <canvas id="previewCanvas" style="max-width: 100%;"></canvas>
              </div>
              <!-- Hidden input field for camera capture -->
              <input type="hidden" id="id_file" name="file">
              <button type="submit" class="btn btn-primary">Submit</button>
          </form>
      </div>
  </div>
</div>


                    
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>PDF Filename</th>
                                    <th>CSV Download</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for receipt_file in receipt_files %}
                                <tr>
                                    <td>{{ receipt_file.pdf_file.file }}
                                      <a
                                            href="{{ url }}{{ receipt_file.pdf_file.file }}">
                                            PDF File
                                        </a>
                                      </td>
                                    <td>{{ receipt_file.csv_file }}
                                        <a
                                            href="{{ url }}{{ receipt_file.csv_file }}">
                                            Download
                                        </a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

       
       
            <script>

              $(document).ready(function () {
                  var cropper;
              
                  $('#fileInput').change(function (event) {
                      var files = event.target.files;
                      var file = files[0];
              
                      if (file.type === 'application/pdf') {
                        // Display PDF
                          displayPDF(file);
                      } else if (file.type.startsWith('image/')) {
                          // Display Image
                          displayImage(file);
                      } else {
                          alert('Unsupported file format!');
                      }
                  });
              
                  function displayPDF(file) {
                      var reader = new FileReader();
                      reader.onload = function (e) {
                          var typedarray = new Uint8Array(e.target.result);
                          pdfjsLib.getDocument(typedarray).promise.then(function (pdf) {
                              pdf.getPage(1).then(function (page) {
                                  var viewport = page.getViewport({ scale: 1 });
                                  var canvas = document.getElementById('previewCanvas');
                                  var context = canvas.getContext('2d');
                                  canvas.height = viewport.height;
                                  canvas.width = viewport.width;
                                  var renderContext = {
                                      canvasContext: context,
                                      viewport: viewport
                                  };
                                  page.render(renderContext).promise.then(function () {
                                      if (cropper) {
                                          cropper.destroy();
                                      }
                                      cropper = new Cropper(canvas, {
                                          viewMode: 1,
                                          dragMode: 'move',
                                          cropBoxResizable: true,
                                          cropBoxMovable: true,
                                          aspectRatio: NaN,
                                          crop: function (event) {
                                              // Do something when crop is done
                                          }
                                      });
                                  });
                              });
                          });
                      };
                      reader.readAsArrayBuffer(file);
                  }
              
                  function displayImage(file) {
                      var reader = new FileReader();
                      reader.onload = function (e) {
                          var image = new Image();
                          image.src = e.target.result;
                          image.onload = function () {
                              var canvas = document.getElementById('previewCanvas');
                              var ctx = canvas.getContext('2d');
                              ctx.clearRect(0, 0, canvas.width, canvas.height);
                              canvas.width = image.width;
                              canvas.height = image.height;
                              ctx.drawImage(image, 0, 0, image.width, image.height);
              
                              // Initialize Cropper
                              cropper = new Cropper(canvas, {
                                  viewMode: 1,
                                  dragMode: 'move',
                                  cropBoxResizable: true,
                                  cropBoxMovable: true,
                                  aspectRatio: NaN,
                                  crop: function (event) {
                                      // Do something when crop is done
                                  }
                              });
                          };
                      };
                      reader.readAsDataURL(file);
                  }
              
              $('#uploadForm').submit(function (event) 
              {
                  event.preventDefault();
                  var files = $('#fileInput')[0].files;
                  
                  if (files.length === 0) {
                      console.error('No file selected.');
                      return;
                  }
              
                  var croppedData = cropper.getData();
                  var croppedImageData = cropper.getCroppedCanvas().toDataURL();
                  var croppedImageBlob = dataURItoBlob(croppedImageData);
              
                  // Get coordinates
                  var leftMargin = parseInt(croppedData.x);
                  var bottomMargin = parseInt(croppedData.y + croppedData.height);
                  var rightMargin = parseInt(croppedData.x + croppedData.width);
                  var topMargin = parseInt(croppedData.y);
              
              
                  
                  var formData = new FormData();
                 
                  formData.append('pdf_file', files[0]); // Pass the first file from the input
                  formData.append('x1', leftMargin);
                  formData.append('y1', bottomMargin);
                  formData.append('x2', rightMargin);
                  formData.append('y2', topMargin);
                  formData.append('croppedImage', croppedImageBlob);
                  
                  console.log("Test");
                  console.log('pdf_file', files[0].name,"\nCoordinates: x1=", leftMargin, " y1=", bottomMargin, " x2=", rightMargin, " y2=", topMargin);
 
$.ajax({
    //url: 'http://localhost:8000/api/upload',
    url: 'https://file-converter-0ndt.onrender.com/api/upload',
    
    type: 'POST',
    data: formData,
    processData: false,
    contentType: false,
    success: function (response) {
        console.log("Backend success");
        console.log(response);
        // Reload the page
        window.location.reload();
    },
    error: function (xhr, status, error) {
        console.log("Backend Error");
        console.error(xhr.responseText);
        // Handle errors of the first API call
    }
});

              });
              
              
              
                  // Function to convert data URI to Blob
                  function dataURItoBlob(dataURI) 
                  {
                      var byteString = atob(dataURI.split(',')[1]);
                      var mimeString = dataURI.split(',')[0].split(':')[1].split(';')[0];
                      var ab = new ArrayBuffer(byteString.length);
                      var ia = new Uint8Array(ab);
                      for (var i = 0; i < byteString.length; i++) 
                      {
                          ia[i] = byteString.charCodeAt(i);
                      }
                      var blob = new Blob([ab], { type: mimeString });
                      return blob;
                  }
              
              });
              
              
              </script>
    </body>
</html>

convertor/templates/success_page.html
<!-- templates/success_page.html -->

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Success Page</title>
    </head>
    <body>
        <h2>Success Page</h2>
        <table border="1">
            <thead>
                <tr>
                    <th>Filename</th>
                    <th>Uploaded At</th>
                </tr>
            </thead>
            <tbody>
                {% for receipt_file in receipt_files %}
                <tr>
                    <td>{{ receipt_file.file.name }}</td>
                    <td>{{ receipt_file.uploaded_at }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </body>
</html>